### ISSUE TITLE
Older webpack version conflicting with new webpack

### ISSUE THREAD

**Issue by jasurabdullin** [learn-co-curriculum/react-presentation-components-lab#22]
Every time I try to `npm install ` on a particular lab, I get a long list of errors with a yellow WARN message to the left of each error. Then, I am recommended to run `npm audit fix`. This work around sometimes worked on some labs, but recently, running `npm start` has been suggesting me to do the following: 

> To fix the dependency tree, try following the steps below in the exact order:
> 1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
>
> 2. Delete node_modules in your project folder.
>
> 3. Remove "webpack" from dependencies and/or devDependencies in the package.json file in your project folder.
>
>   4. Run npm install or yarn, depending on the package manager you use.
>
> In most cases, this should be enough to fix the problem.
> If this has not helped, there are a few other things you can try:
> 
>   5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
>      This may help because npm has known issues with package hoisting which may get resolved in future versions.
> 
>   6. Check if /Users/jasurabdullin/Desktop/flatironschool/4-module/6-advanced-components/react-presentation-components-lab-dc-web-102819/node_modules/webpack is outside your project directory.
>      For example, you might have accidentally installed something in your home folder.
> 
>   7. Try running npm ls webpack in your project folder.
>      This will tell you which other package (apart from the expected react-scripts) installed webpack.

Previously, I was executing Step 1-4 after which running `npm start` would work and start the `react-server`

However, for this lab, none of my previous fixes are working. Should I install yarn or is this a different kind of issue?

**Comment by Sdcrouse** [comment]
I ran into that, too. The solution I found (after re-cloning the lab) was to avoid running `npm install` or `npm audit fix` in the first place. `npm start` then works as intended.

Evidently, running `npm install` and/or `npm audit fix`, installs or upgrades a few dependencies that conflict with others in this lab.
